name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Run build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Set up node and add the registry url
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      # Build release assets
      - name: Build release assets
        run: |
          npm run build
