name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up node and add the registry url
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      # Install
      - name: Install
        run: npm ci

      - name: Install Playwright Browsers
        run: |
          npx playwright install chromium
          sudo apt-get update
          sudo apt-get install -y libnss3 libatk-bridge2.0-0 libdrm2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxfixes3 libxkbcommon0 libasound2t64

      # Test
      - name: Run tests
        run: npm run test
